# Generated by Django 3.1.7 on 2021-05-04 21:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('medical_certification', models.CharField(choices=[('CPR', 'CPR'), ('First Aid', 'First Aid'), ('Both', 'Both'), ('None', 'None')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_size', models.IntegerField()),
                ('time', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], max_length=2)),
                ('class_age', models.CharField(choices=[('YY', 'Younger Youth (7-10)'), ('OY', 'Older Youth (11-15)'), ('AY', 'All Youth (7-15)')], max_length=2)),
                ('assistants', models.IntegerField()),
                ('instructor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.instructor')),
            ],
        ),
    ]
