# Generated by Django 3.1.7 on 2021-05-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.IntegerField(default=2021),
        ),
    ]
