# Generated by Django 3.1.7 on 2021-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='inventory',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
