# Generated by Django 3.1.7 on 2021-05-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_class_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Athletic', 'Athletic'), ('Creative', 'Creative')], default='Academic', max_length=8),
            preserve_default=False,
        ),
    ]
